######################################################################
##
## Filename: tb_axi_ppm.udo
## Created on: Fri Jan 17 09:15:08 AM CST 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################

add wave -r sim:/tb_axi_ppm/uut/USER_LOGIC_I/*

run 120ms